from odoo import models, fields

class Affiliate(models.Model):
    _name = 'cxn.affiliate'
    _inherit = 'res.partner'
    _description = 'Affiliate'

    code = fields.Char(string='Affiliate Code', help='Unique code for the affiliate')
    commission_rate = fields.Float(string='Commission Rate', help='Commission rate for bookings generated by this affiliate')
    account_id = fields.Many2one('account.account', string='Account')
    booking_ids = fields.One2many('sale.order', 'affiliate_id', string='Bookings')
